from building import *

cwd = GetCurrentDir()

if GetDepend('RT_USING_LWIP141'):
    src = ['dhcp_server.c']
else:
    src = ['dhcp_server_raw.c']

CPPPATH = [cwd]

group = DefineGroup('lwIP', src, depend = ['RT_USING_LWIP', 'LWIP_USING_DHCPD'], CPPPATH = CPPPATH)

Return('group')
